workflows:
  run-tests-workflow:
    name: Run Tests Workflow
    max_build_duration: 70
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      groups:
        - MAPBOX_SECRETS

    triggering:
      events:
        - pull_request
        - push
      branch_patterns:
        - pattern: "master"
          include: true
          source: false
        - pattern: "dev"
          include: true
          source: false

    scripts:
      - name: Create .env file
        script: |
          echo "MAPBOX_PUBLIC_TOKEN=$MAPBOX_PUBLIC_TOKEN" > .env
          echo "MAPBOX_SECRET_TOKEN=$MAPBOX_SECRET_TOKEN" >> .env
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test

    publishing:
      email:
        recipients:
          - engelmmanuel@gmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: '#publish'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  publish-to-slack-channel-workflow:
    name: Publish to Slack Channel Workflow
    max_build_duration: 90
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      groups:
        - MAPBOX_SECRETS

    triggering:
      events:
        - pull_request
        - push
      branch_patterns:
        - pattern: "master"
          include: true
          source: false
        - pattern: "dev"
          include: true
          source: false

    scripts:
      - name: Create .env file
        script: |
          echo "MAPBOX_PUBLIC_TOKEN=$MAPBOX_PUBLIC_TOKEN" > .env
          echo "MAPBOX_SECRET_TOKEN=$MAPBOX_SECRET_TOKEN" >> .env
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build debug apk
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - engelmmanuel@gmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: '#publish'
        notify_on_build_start: true
        notify:
          success: true
          failure: true