name: nim_track
description: A mobile app interface for an IoT-enabled animal tracking system

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc: ^8.1.1
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
   assets:
     - assets/certificates
     - .env
