name: nim_track
description: A mobile app interface for an IoT-enabled animal tracking system

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.6.0
  amplify_flutter: ^1.1.1
  mapbox_maps_flutter: ^0.4.4
  amplify_api: ^1.2.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  path_provider: ^2.0.15
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^22.2.7
  latlong2: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/images/launcher_icon.png"

flutter_native_splash:
  background_image: "assets/images/launcher_icon.png"
