name: nim_track
description: A mobile app interface for an IoT-enabled animal tracking system

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.6.0
  amplify_flutter: ^1.1.0
  google_maps_flutter: ^2.2.8

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
#  assets:
#    - assets/certificates
#    - .env
